version: '3'

services: 
    app:
        build: ./
        container_name: my-nginx-node
        command: npm start
        volumes:
          - .:/usr/src/app
         

    nginx:
        container_name: my-nginx-js
        image: nginx
        ports:
            - "8522:80"
        volumes:
        - ./conf:/etc/nginx/conf.d/
